//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.18 at 10:14:20 AM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://myprojects.net/xsd/TestScheme", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.jaxbsample;
