//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.01 at 06:35:43 PM IST 
//


package com.jaxb.testjunit;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.jaxb.testjunit package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Testsuite_QNAME = new QName("", "testsuite");
    private final static QName _TestcaseTypeFailure_QNAME = new QName("", "failure");
    private final static QName _TestcaseTypeError_QNAME = new QName("", "error");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.jaxb.testjunit
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TestsuiteType }
     * 
     */
    public TestsuiteType createTestsuiteType() {
        return new TestsuiteType();
    }

    /**
     * Create an instance of {@link FailureType }
     * 
     */
    public FailureType createFailureType() {
        return new FailureType();
    }

    /**
     * Create an instance of {@link ErrorType }
     * 
     */
    public ErrorType createErrorType() {
        return new ErrorType();
    }

    /**
     * Create an instance of {@link TestcaseType }
     * 
     */
    public TestcaseType createTestcaseType() {
        return new TestcaseType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TestsuiteType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "testsuite")
    public JAXBElement<TestsuiteType> createTestsuite(TestsuiteType value) {
        return new JAXBElement<TestsuiteType>(_Testsuite_QNAME, TestsuiteType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FailureType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "failure", scope = TestcaseType.class)
    public JAXBElement<FailureType> createTestcaseTypeFailure(FailureType value) {
        return new JAXBElement<FailureType>(_TestcaseTypeFailure_QNAME, FailureType.class, TestcaseType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ErrorType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "error", scope = TestcaseType.class)
    public JAXBElement<ErrorType> createTestcaseTypeError(ErrorType value) {
        return new JAXBElement<ErrorType>(_TestcaseTypeError_QNAME, ErrorType.class, TestcaseType.class, value);
    }

}
