


/**
 * @author srivatsan
 */
public interface HierarchicalAssetDBQueryConstants {

	/*---------------------------------HierarchicalAsset payload constants------------------------------*/
	String COLUMN_ASSET_PAYLOAD_TOPIC_ID = "TOPIC_ID";
	String COLUMN_ASSET_PAYLOAD_ASSET_PAYLOAD = "ASSET_PAYLOAD";
	String COLUMN_ASSET_PAYLOAD_ASSET_DATA = "ASSET_DATA";
	String COLUMN_ASSET_PAYLOAD_ASSET_PART_NUM = "ASSET_PART_NUM";

	/*---------------------------------HierarchicalAsset state constants-------------*/
	String COLUMN_ASSET_STATE_STRIPE_INDEX = "STRIPE_INDEX";
	String COLUMN_ASSET_STATE_ASSET_KEY = "ASSET_KEY";
	String COLUMN_ASSET_STATE_SITE_ID = "SITE_ID";
	String COLUMN_ASSET_STATE_ASSET_VERSION = "ASSET_VERSION";
	String COLUMN_ASSET_STATE_ASSET_VECTOR = "ASSET_VECTOR";
	String COLUMN_ASSET_STATE_ASSET_SITE_ID = "ASSET_SITE_ID";
	String COLUMN_ASSET_STATE_ASSET_CREATE_TM = "CREATE_TM";
	String COLUMN_ASSET_STATE_ASSET_EXPIRATION_TM = "EXPIRATION_TM";
	String COLUMN_ASSET_STATE_ASSET_DELETE_IND = "ASSET_DELETE_IND";
	String COLUMN_ASSET_STATE_OWNER_SITE_ID = "OWNER_SITE_ID";
	String COLUMN_ASSET_STATE_ASSET_SEQ_NUM = "ASSET_SEQ_NUM";
	String COLUMN_ASSET_STATE_ASSET_TOTAL_PARTS = "ASSET_TOTAL_PARTS";
	String COLUMN_ASSET_STATE_ASSET_LENGTH = "ASSET_LENGTH";
	String COLUMN_ASSET_STATE_ASSET_PART_SIZE = "ASSET_PART_SIZE";
	String COLUMN_ASSET_STATE_ASSET_STORED_LENGTH = "ASSET_STORED_LENGTH";
	String COLUMN_ASSET_STATE_ASSET_CHECKSUM = "ASSET_CHECKSUM";
	String COLUMN_ASSET_STATE_MOUNT_ID = "MOUNT_ID";
	String COLUMN_ASSET_STATE_MOUNT_FILE_PATH = "MOUNT_FILE_PATH";
	String COLUMN_ASSET_STATE_VIRUS_SCAN_DEFN = "VIRUS_SCAN_DEFN";
	String COLUMN_ASSET_STATE_VIRUS_SCAN_DEFN_TM = "VIRUS_SCAN_DEFN_TM";
	String COLUMN_ASSET_STATE_VIRUS_SCAN_STATUS = "VIRUS_SCAN_STATUS";
	String COLUMN_ASSET_STATE_VIRUS_SCAN_TM = "VIRUS_SCAN_TM";
	String COLUMN_ASSET_STATE_FS_VERSION = "FS_VERSION";
	String COLUMN_ASSET_STATE_ASSET_MIGRATION_TM = "MIGRATION_TM";
	String COLUMN_ASSET_STATE_ASSET_BUCKET = "ASSET_BUCKET";
	String COLUMN_ASSET_STATE_ASSET_PATH = "ASSET_PATH";
	String COLUMN_ASSET_STATE_ASSET_METADATA = "ASSET_METADATA";
	String COLUMN_ASSET_STATE_ASSET_TYPE = "ASSET_TYPE";
	String COLUMN_ASSET_STATE_ASSET_TYPE_IND = "ASSET_TYPE_IND";

	/*---------------------------------HierarchicalAsset TEMP state Constants----------------------------*/

	String TABLE_AST_TEMP = "GNV_AST_TEMP";
	String COLUMN_ASSET_TEMP_ASSET_SEQ_NUM = "ASSET_SEQ_NUM";
	String COLUMN_ASSET_TEMP_ASSET_VERSION = "ASSET_VERSION";
	String COLUMN_ASSET_TEMP_ASSET_TOTAL_PARTS = "ASSET_TOTAL_PARTS";
	String COLUMN_ASSET_TEMP_ASSET_PART_SIZE = "ASSET_PART_SIZE";
	String COLUMN_ASSET_TEMP_ASSET_STORED_PARTS = "ASSET_STORED_PARTS";
	String COLUMN_ASSET_TEMP_ASSET_STORED_LENGTH = "ASSET_STORED_LENGTH";
	String COLUMN_ASSET_TEMP_ASSET_TOTAL_LENGTH = "ASSET_TOTAL_LENGTH";
	String COLUMN_ASSET_TEMP_CREATE_TM = "CREATE_TM";
	String COLUMN_ASSET_TEMP_ASSET_TTL_VALUE = "ASSET_TTL_VALUE";
	String COLUMN_ASSET_TEMP_ASSET_METADATA = "ASSET_METADATA";
	String COLUMN_ASSET_TEMP_ASSET_PATH = "ASSET_PATH";
	String COLUMN_ASSET_TEMP_ASSET_TYPE_IND = "ASSET_TYPE_IND";


	String COLUMN_TAG_ = "TAG_";


	String SELECT_KEY_COUNT_FOR_AST_TABLE =
			" /* HA_QRY_1 */ SELECT COUNT( DISTINCT ASSET_KEY), SUM( ASSET_LENGTH ) FROM %TABLENAME% WHERE ASSET_DELETE_IND!=1";

	String UPDATE_ASSET_FINAL_STATE_VIRUSSCAN_INFO_VERSION = " /* HA_QRY_2 */ UPDATE /*+ INDEX( %TABLENAME_UQF% %TABLENAME_UQF%_PK ) */ %TABLENAME% SET VIRUS_SCAN_STATUS=?, VIRUS_SCAN_DEFN=?,"
			+ "VIRUS_SCAN_DEFN_TM=?, VIRUS_SCAN_TM=?, ASSET_SEQ_NUM=? "
			+ "WHERE STRIPE_INDEX=? AND ASSET_BUCKET=? AND ASSET_KEY=? AND SITE_ID=? AND TOPIC_ID=? AND CREATE_TM=? AND ASSET_VERSION=?";

	String UPDATE_ASSET_FINAL_STATE_VIRUSSCAN_INFO = " /* HA_QRY_3 */ UPDATE /*+ INDEX( %TABLENAME_UQF% %TABLENAME_UQF%_PK ) */ %TABLENAME% SET VIRUS_SCAN_STATUS=?, VIRUS_SCAN_DEFN=?,"
			+ "VIRUS_SCAN_DEFN_TM=?, VIRUS_SCAN_TM=?, ASSET_SEQ_NUM=? "
			+ "WHERE STRIPE_INDEX=? AND ASSET_BUCKET=? AND ASSET_KEY=? AND SITE_ID=? AND TOPIC_ID=? AND CREATE_TM=?";

	String QUERY_GET_AST_TEMP_STATE_SEQ =
			" /* HA_QRY_4 */ SELECT /*+ INDEX(%TABLENAME% %TABLENAME%_PK) */ ASSET_STORED_PARTS,ASSET_TOTAL_PARTS,ASSET_PART_SIZE," +
					"ASSET_STORED_LENGTH,ASSET_TOTAL_LENGTH,ASSET_SEQ_NUM,ASSET_TTL_VALUE,CREATE_TM,ASSET_VERSION," +
					"ASSET_PATH,ASSET_TYPE_IND,ASSET_METADATA, TAG_1 , TAG_2 , TAG_3 , TAG_4 , TAG_5 , TAG_6 , " +
					"TAG_7 , TAG_8 , TAG_9 , TAG_10, TAG_11, TAG_12, TAG_13, TAG_14, TAG_15, TAG_16, TAG_17, TAG_18, " +
					"TAG_19, TAG_20, TAG_21, TAG_22, TAG_23, TAG_24, TAG_25, TAG_26, TAG_27, TAG_28, TAG_29, TAG_30, " +
					"TAG_31, TAG_32 FROM %TABLENAME% WHERE STRIPE_INDEX=? AND ASSET_KEY= ? AND SITE_ID= ? AND " +
					"TOPIC_ID= ? AND ASSET_BUCKET= ?";

	String GET_FILE_COUNT_BUCKET =
			" /* HA_QRY_5 */ SELECT COUNT(*) FROM (SELECT /*+ INDEX(%TABLENAME_UQF% %TABLENAME_UQF%_PK) */ ASSET_KEY, " +
					"ASSET_DELETE_IND, ROW_NUMBER() OVER (PARTITION BY STRIPE_INDEX, ASSET_BUCKET, " +
					"ASSET_KEY ORDER BY CREATE_TM DESC) DUP FROM %TABLENAME% WHERE ASSET_BUCKET = ? AND STRIPE_INDEX = ? AND " +
					"ASSET_TYPE_IND = 0) A  WHERE A.DUP = 1 AND A.ASSET_DELETE_IND != 1";

	String GET_FILE_COUNT_BUCKET_MIGRATING =
			" /* HA_QRY_6 */ SELECT COUNT(*) FROM (SELECT /*+ INDEX(%TABLENAME_UQF% %TABLENAME_UQF%_PK) */ ASSET_KEY, " +
					"ASSET_DELETE_IND, ROW_NUMBER() OVER (PARTITION BY STRIPE_INDEX, ASSET_BUCKET, " +
					"ASSET_KEY ORDER BY CREATE_TM DESC) DUP FROM "
					+ "( SELECT /*+ INDEX(%TABLENAME_UQF% %TABLENAME_UQF%_PK) */ ASSET_KEY, ASSET_DELETE_IND, STRIPE_INDEX, ASSET_BUCKET, CREATE_TM "
					+ "FROM ROM %TABLENAME% WHERE ASSET_BUCKET = ? AND STRIPE_INDEX = ? AND ASSET_TYPE_IND = 0"
					+ " UNION "
					+ " SELECT /*+ INDEX(%TABLENAME_UQF% %TABLENAME_UQF%_PK) */ ASSET_KEY, ASSET_DELETE_IND, STRIPE_INDEX, ASSET_BUCKET, CREATE_TM "
					+ "FROM ROM %TABLENAME%@%DBLINK% WHERE ASSET_BUCKET = ? AND STRIPE_INDEX = ? AND ASSET_TYPE_IND = 0)"
					+ ") A  WHERE A.DUP = 1 AND A.ASSET_DELETE_IND != 1";

	String GET_FILE_COUNT_FOLDER =
			" /* HA_QRY_7 */ SELECT COUNT(*) FROM (SELECT /*+ INDEX(%TABLENAME_UQF% %TABLENAME_UQF%_PK) */ ASSET_KEY, " +
					"ASSET_DELETE_IND, ROW_NUMBER() OVER (PARTITION BY STRIPE_INDEX, ASSET_BUCKET, " +
					"ASSET_KEY ORDER BY CREATE_TM DESC) DUP FROM %TABLENAME% WHERE ASSET_BUCKET = ? AND STRIPE_INDEX = ? AND " +
					"ASSET_TYPE_IND = 0 AND TAG_%FOLDER_LEVEL%= ?) A  WHERE A.DUP = 1 AND A.ASSET_DELETE_IND != 1";

	String GET_FILE_COUNT_FOLDER_MIGRATING =
			" /* HA_QRY_8 */ SELECT COUNT(*) FROM (SELECT /*+ INDEX(%TABLENAME_UQF% %TABLENAME_UQF%_PK) */ ASSET_KEY, " +
					"ASSET_DELETE_IND, ROW_NUMBER() OVER (PARTITION BY STRIPE_INDEX, ASSET_BUCKET, " +
					"ASSET_KEY ORDER BY CREATE_TM DESC) DUP FROM "
					+ "( SELECT /*+ INDEX(%TABLENAME_UQF% %TABLENAME_UQF%_PK) */ ASSET_KEY, ASSET_DELETE_IND, STRIPE_INDEX, ASSET_BUCKET, CREATE_TM "
					+ "FROM ROM %TABLENAME% WHERE ASSET_BUCKET = ? AND STRIPE_INDEX = ? AND ASSET_TYPE_IND = 0 AND TAG_%FOLDER_LEVEL%= ?"
					+ " UNION "
					+ " SELECT /*+ INDEX(%TABLENAME_UQF% %TABLENAME_UQF%_PK) */ ASSET_KEY, ASSET_DELETE_IND, STRIPE_INDEX, ASSET_BUCKET, CREATE_TM "
					+ "FROM ROM %TABLENAME%@%DBLINK% WHERE ASSET_BUCKET = ? AND STRIPE_INDEX = ? AND ASSET_TYPE_IND = 0 AND TAG_%FOLDER_LEVEL%= ?)"
					+ ") A  WHERE A.DUP = 1 AND A.ASSET_DELETE_IND != 1";
	
	String GET_FILE_IDS_FOLDER =
			" /* HA_QRY_9 */ SELECT ASSET_KEY, ASSET_PATH FROM (SELECT /*+ INDEX(%TABLENAME_UQF% %TABLENAME_UQF%_PK) */ ASSET_KEY, " +
					"ASSET_DELETE_IND, ASSET_PATH, ROW_NUMBER() OVER (PARTITION BY STRIPE_INDEX, ASSET_BUCKET, " +
					"ASSET_KEY ORDER BY CREATE_TM DESC) DUP FROM %TABLENAME% WHERE ASSET_BUCKET = ? AND STRIPE_INDEX = ? AND " +
					"ASSET_TYPE_IND = 0 AND TAG_%FOLDER_LEVEL%= ?) A WHERE A.DUP = 1 AND A.ASSET_DELETE_IND != 1";

	String GET_FILE_IDS_FOLDER_WITH_DEPTH =
			" /* HA_QRY_10 */ SELECT ASSET_KEY, ASSET_PATH FROM (SELECT /*+ INDEX(%TABLENAME_UQF% %TABLENAME_UQF%_PK) */ ASSET_KEY, " +
					"ASSET_DELETE_IND, ASSET_PATH, ROW_NUMBER() OVER (PARTITION BY STRIPE_INDEX, ASSET_BUCKET, " +
					"ASSET_KEY ORDER BY CREATE_TM DESC) DUP FROM %TABLENAME% WHERE ASSET_BUCKET = ? AND STRIPE_INDEX = ? AND " +
					"TAG_%FOLDER_LEVEL%= ? AND ASSET_TYPE_IND = 0 AND TAG_%END_DEPTH_FILE% IS NULL) A "+
					"WHERE A.DUP = 1 AND A.ASSET_DELETE_IND != 1";

	String GET_FILE_IDS_BUCKET =
			" /* HA_QRY_11 */ SELECT ASSET_KEY, ASSET_PATH FROM (SELECT /*+ INDEX(%TABLENAME_UQF% %TABLENAME_UQF%_PK) */ ASSET_KEY, " +
					"ASSET_DELETE_IND, ASSET_PATH, ROW_NUMBER() OVER (PARTITION BY STRIPE_INDEX, ASSET_BUCKET, " +
					"ASSET_KEY ORDER BY CREATE_TM DESC) DUP FROM %TABLENAME% WHERE ASSET_BUCKET = ? AND STRIPE_INDEX = ? AND " +
					"ASSET_TYPE_IND = 0) A WHERE A.DUP = 1 AND A.ASSET_DELETE_IND != 1";

	String GET_FILE_IDS_BUCKET_WITH_DEPTH  =
			" /* HA_QRY_12 */ SELECT ASSET_KEY, ASSET_PATH FROM (SELECT /*+ INDEX(%TABLENAME_UQF% %TABLENAME_UQF%_PK) */ ASSET_KEY, " +
					"ASSET_DELETE_IND, ASSET_PATH, ROW_NUMBER() OVER (PARTITION BY STRIPE_INDEX, ASSET_BUCKET, " +
					"ASSET_KEY ORDER BY CREATE_TM DESC) DUP FROM %TABLENAME% WHERE ASSET_BUCKET = ? AND STRIPE_INDEX = ? AND " +
					"ASSET_TYPE_IND = 0 AND TAG_%END_DEPTH_FILE% IS NULL) A WHERE A.DUP = 1 AND A.ASSET_DELETE_IND != 1";

	String GET_DISTINCT_FOLDER_FOR_BUCKET = " /* HA_QRY_13 */ SELECT DISTINCT(TAG_%END_DEPTH_FOLDER%) FROM ("
			+ "SELECT /*+ INDEX(%TABLENAME_UQF% %TABLENAME_UQF%_PK) */ ASSET_DELETE_IND, TAG_%END_DEPTH_FOLDER%, "
			+ "ROW_NUMBER() OVER (PARTITION BY STRIPE_INDEX, ASSET_BUCKET, ASSET_KEY ORDER BY CREATE_TM DESC) DUP "
			+ "FROM %TABLENAME% WHERE ASSET_BUCKET = ? AND STRIPE_INDEX = ?  AND TAG_%END_DEPTH_FOLDER% IS NOT NULL) A "
			+ "WHERE A.DUP = 1 AND A.ASSET_DELETE_IND != 1";
	
	String GET_DISTINCT_FOLDER_FOR_FOLDER = " /* HA_QRY_14 */ SELECT DISTINCT(TAG_%END_DEPTH_FOLDER%) FROM ("
			+ "SELECT /*+ INDEX(%TABLENAME_UQF% %TABLENAME_UQF%_PK) */ ASSET_DELETE_IND, TAG_%END_DEPTH_FOLDER%, "
			+ "ROW_NUMBER() OVER (PARTITION BY STRIPE_INDEX, ASSET_BUCKET, ASSET_KEY ORDER BY CREATE_TM DESC) DUP "
			+ "FROM %TABLENAME% WHERE ASSET_BUCKET = ? AND STRIPE_INDEX = ? AND TAG_%FOLDER_LEVEL% = ? AND TAG_%END_DEPTH_FOLDER% IS NOT NULL) A "
			+ "WHERE A.DUP = 1 AND A.ASSET_DELETE_IND != 1";
	
	String QUERY_AST_STATE_WITH_DELETE_INFO =
			" /* HA_QRY_15 */ SELECT /*+ INDEX(%TABLENAME_UQF% %TABLENAME_UQF%_PK) */ SITE_ID, ASSET_VERSION, OWNER_SITE_ID, " +
					"ASSET_SITE_ID, ASSET_VECTOR, ASSET_SEQ_NUM, CREATE_TM, EXPIRATION_TM, MIGRATION_TM, " +
					"ASSET_DELETE_IND, ASSET_TOTAL_PARTS, ASSET_PART_SIZE, ASSET_LENGTH, ASSET_STORED_LENGTH, ASSET_TYPE, " +
					"ASSET_CHECKSUM, MOUNT_ID, VIRUS_SCAN_STATUS, VIRUS_SCAN_DEFN, VIRUS_SCAN_DEFN_TM, VIRUS_SCAN_TM," +
					" FS_VERSION, ASSET_METADATA, ASSET_PATH, ASSET_TYPE_IND, MOUNT_FILE_PATH FROM %TABLENAME% WHERE STRIPE_INDEX=? " +
					"AND ASSET_KEY=? AND ASSET_BUCKET=?";

	String QUERY_AST_STATE_WITH_DELETE_INFO_GIVEN_SITE =
			" /* HA_QRY_16 */ SELECT /*+ INDEX(%TABLENAME_UQF% %TABLENAME_UQF%_PK) */ SITE_ID, ASSET_VERSION, OWNER_SITE_ID, " +
					"ASSET_SITE_ID, ASSET_VECTOR, ASSET_SEQ_NUM, CREATE_TM, EXPIRATION_TM, MIGRATION_TM, " +
					"ASSET_DELETE_IND, ASSET_TOTAL_PARTS, ASSET_PART_SIZE, ASSET_LENGTH, ASSET_STORED_LENGTH, ASSET_TYPE, " +
					"ASSET_CHECKSUM, MOUNT_ID, VIRUS_SCAN_STATUS, VIRUS_SCAN_DEFN, VIRUS_SCAN_DEFN_TM, VIRUS_SCAN_TM," +
					" FS_VERSION, ASSET_METADATA, ASSET_PATH, ASSET_TYPE_IND, MOUNT_FILE_PATH FROM %TABLENAME% WHERE STRIPE_INDEX=? " +
					"AND ASSET_KEY=? AND ASSET_BUCKET=? AND ASSET_SITE_ID = ?";

	String QUERY_AST_STATE_WITH_DELETE_INFO_TREE_WITH_LEVEL_DEPTH =
			" /* HA_QRY_17 */ SELECT /*+ INDEX(%TABLENAME_UQF% %TABLENAME_UQF%_PK) */ SITE_ID, ASSET_VERSION, SITE_ID, ASSET_SITE_ID, " +
					"MOUNT_ID, MOUNT_FILE_PATH, OWNER_SITE_ID, ASSET_VECTOR, CREATE_TM, EXPIRATION_TM, ASSET_DELETE_IND, " +
					"ASSET_METADATA, ASSET_TYPE_IND, ASSET_PATH, ASSET_KEY, ASSET_TOTAL_PARTS, MIGRATION_TM, " +
					"ASSET_CHECKSUM, ASSET_PART_SIZE, ASSET_LENGTH, ASSET_STORED_LENGTH, VIRUS_SCAN_STATUS, VIRUS_SCAN_DEFN, " +
					"VIRUS_SCAN_DEFN_TM, ASSET_SEQ_NUM FROM %TABLENAME% WHERE ASSET_BUCKET = ? AND STRIPE_INDEX = ? " +
					"AND TAG_%START_DEPTH% = ? AND ((ASSET_TYPE_IND = 0 AND TAG_%END_DEPTH_FILE% IS NULL) OR (ASSET_TYPE_IND = 1 AND TAG_%END_DEPTH_FOLDER% IS NULL) OR ASSET_TYPE_IND = 2)";

	String QUERY_AST_STATE_WITH_DELETE_INFO_TREE_WITH_LEVEL =
			" /* HA_QRY_18 */ SELECT /*+ INDEX(%TABLENAME_UQF% %TABLENAME_UQF%_PK) */ SITE_ID, ASSET_VERSION, SITE_ID, ASSET_SITE_ID, " +
					"MOUNT_ID, MOUNT_FILE_PATH, OWNER_SITE_ID, ASSET_VECTOR, CREATE_TM, EXPIRATION_TM, ASSET_DELETE_IND, " +
					"ASSET_METADATA, ASSET_TYPE_IND, ASSET_PATH, ASSET_KEY, ASSET_TOTAL_PARTS, MIGRATION_TM, " +
					"ASSET_CHECKSUM, ASSET_PART_SIZE, ASSET_LENGTH, ASSET_STORED_LENGTH, VIRUS_SCAN_STATUS, VIRUS_SCAN_DEFN, " +
					"VIRUS_SCAN_DEFN_TM, ASSET_SEQ_NUM FROM %TABLENAME% WHERE ASSET_BUCKET = ? " +
					"AND STRIPE_INDEX = ? AND TAG_%START_DEPTH%= ?";

	String QUERY_AST_STATE_WITH_DELETE_INFO_TREE_WITH_DEPTH =
			" /* HA_QRY_19 */ SELECT /*+ INDEX(%TABLENAME_UQF% %TABLENAME_UQF%_PK) */ SITE_ID, ASSET_VERSION, SITE_ID, ASSET_SITE_ID, " +
					"MOUNT_ID, MOUNT_FILE_PATH, OWNER_SITE_ID, ASSET_VECTOR, CREATE_TM, EXPIRATION_TM, ASSET_DELETE_IND, " +
					"ASSET_METADATA, ASSET_TYPE_IND, ASSET_PATH, ASSET_KEY, ASSET_TOTAL_PARTS, MIGRATION_TM, " +
					"ASSET_CHECKSUM, ASSET_PART_SIZE, ASSET_LENGTH, ASSET_STORED_LENGTH, VIRUS_SCAN_STATUS, VIRUS_SCAN_DEFN, " +
					"VIRUS_SCAN_DEFN_TM, ASSET_SEQ_NUM FROM %TABLENAME% WHERE ASSET_BUCKET = ? " +
					"AND STRIPE_INDEX = ? AND ((ASSET_TYPE_IND = 0 AND TAG_%END_DEPTH_FILE% IS NULL) OR (ASSET_TYPE_IND = 1 AND TAG_%END_DEPTH_FOLDER% IS NULL) OR ASSET_TYPE_IND = 2)";

	String QUERY_AST_STATE_WITH_DELETE_INFO_TREE =
			" /* HA_QRY_20 */ SELECT /*+ INDEX(%TABLENAME_UQF% %TABLENAME_UQF%_PK) */ SITE_ID, ASSET_VERSION, SITE_ID, ASSET_SITE_ID, " +
					"MOUNT_ID, MOUNT_FILE_PATH, OWNER_SITE_ID, ASSET_VECTOR, CREATE_TM, EXPIRATION_TM, ASSET_DELETE_IND, " +
					"ASSET_METADATA, ASSET_TYPE_IND, ASSET_PATH, ASSET_KEY, ASSET_TOTAL_PARTS, MIGRATION_TM, " +
					"ASSET_CHECKSUM, ASSET_PART_SIZE, ASSET_LENGTH, ASSET_STORED_LENGTH, VIRUS_SCAN_STATUS, VIRUS_SCAN_DEFN, " +
					"VIRUS_SCAN_DEFN_TM, ASSET_SEQ_NUM FROM %TABLENAME% WHERE ASSET_BUCKET = ? AND STRIPE_INDEX = ?";

	String QUERY_UPDATE_FINAL_STATE_DELETE_PART =
			" /* HA_QRY_21 */ MERGE /*+ INDEX( %TABLENAME_UQF% %TABLENAME_UQF%_PK ) */ INTO %TABLENAME% STATE USING (SELECT  ? " +
					"STRIPE_INDEX, ? ASSET_KEY, ? SITE_ID, ? TOPIC_ID, ? ASSET_SITE_ID, ? OWNER_SITE_ID, ? CREATE_TM," +
					" ? EXPIRATION_TM, ? MIGRATION_TM, ? ASSET_VERSION, ? ASSET_OLD_VERSION, ? ASSET_SEQ_NUM, " +
					"? ASSET_VECTOR, ? ASSET_TOTAL_PARTS, ? ASSET_LENGTH, ? ASSET_STORED_LENGTH, ? ASSET_TYPE, " +
					"? ASSET_CHECKSUM, ? ASSET_DELETE_IND, ? MOUNT_ID, ? VIRUS_SCAN_STATUS, ? VIRUS_SCAN_DEFN, " +
					"? VIRUS_SCAN_DEFN_TM, ? VIRUS_SCAN_TM, ? FS_VERSION, ? ASSET_BUCKET, ? ASSET_PATH, " +
					"? ASSET_TYPE_IND, ? ASSET_METADATA, ? ASSET_PART_SIZE FROM DUAL) NEWSTATE ON (( STATE.STRIPE_INDEX " +
					"=NEWSTATE.STRIPE_INDEX AND STATE.ASSET_KEY=NEWSTATE.ASSET_KEY AND STATE.ASSET_BUCKET=NEWSTATE" +
					".ASSET_BUCKET AND STATE.SITE_ID=NEWSTATE.SITE_ID)) WHEN MATCHED THEN  UPDATE SET  STATE" +
					".ASSET_SITE_ID=NEWSTATE.ASSET_SITE_ID, STATE.ASSET_VERSION=NEWSTATE.ASSET_VERSION, " +
					"STATE.ASSET_VECTOR=NEWSTATE.ASSET_VECTOR, STATE.ASSET_DELETE_IND=NEWSTATE.ASSET_DELETE_IND, " +
					"STATE.CREATE_TM=NEWSTATE.CREATE_TM WHERE  STATE.ASSET_VERSION=NEWSTATE.ASSET_OLD_VERSION WHEN " +
					"NOT MATCHED THEN  INSERT (  STATE.STRIPE_INDEX, STATE.ASSET_KEY, STATE.SITE_ID, STATE.TOPIC_ID, " +
					"STATE.ASSET_SITE_ID, STATE.OWNER_SITE_ID, STATE.ASSET_VERSION, STATE.ASSET_VECTOR, " +
					"STATE.ASSET_SEQ_NUM, STATE.CREATE_TM, STATE.EXPIRATION_TM, STATE.MIGRATION_TM, " +
					"STATE.ASSET_TOTAL_PARTS, STATE.ASSET_LENGTH, STATE.ASSET_STORED_LENGTH, STATE.ASSET_TYPE, " +
					"STATE.ASSET_CHECKSUM, STATE.ASSET_DELETE_IND, STATE.MOUNT_ID, STATE.VIRUS_SCAN_STATUS, " +
					"STATE.VIRUS_SCAN_DEFN, STATE.VIRUS_SCAN_DEFN_TM, STATE.VIRUS_SCAN_TM, STATE.FS_VERSION, " +
					"STATE.ASSET_BUCKET, STATE.ASSET_PATH, STATE.ASSET_TYPE_IND, STATE.ASSET_METADATA, " +
					"STATE.ASSET_PART_SIZE ) VALUES ( NEWSTATE.STRIPE_INDEX, NEWSTATE.ASSET_KEY, NEWSTATE.SITE_ID, " +
					"NEWSTATE.TOPIC_ID, NEWSTATE.ASSET_SITE_ID, NEWSTATE.OWNER_SITE_ID, NEWSTATE.ASSET_VERSION, " +
					"NEWSTATE.ASSET_VECTOR, NEWSTATE.ASSET_SEQ_NUM, NEWSTATE.CREATE_TM, NEWSTATE.EXPIRATION_TM, " +
					"NEWSTATE.MIGRATION_TM, NEWSTATE.ASSET_TOTAL_PARTS, NEWSTATE.ASSET_LENGTH, " +
					"NEWSTATE.ASSET_STORED_LENGTH, NEWSTATE.ASSET_TYPE, NEWSTATE.ASSET_CHECKSUM, " +
					"NEWSTATE.ASSET_DELETE_IND, NEWSTATE.MOUNT_ID, NEWSTATE.VIRUS_SCAN_STATUS, " +
					"NEWSTATE.VIRUS_SCAN_DEFN, NEWSTATE.VIRUS_SCAN_DEFN_TM, NEWSTATE.VIRUS_SCAN_TM, " +
					"NEWSTATE.FS_VERSION, NEWSTATE.ASSET_BUCKET, NEWSTATE.ASSET_PATH, NEWSTATE.ASSET_TYPE_IND, " +
					"NEWSTATE.ASSET_METADATA, NEWSTATE.ASSET_PART_SIZE)";

	String QUERY_UPDATE_FINAL_STATE_DELETE_ALL_PART =
			" /* HA_QRY_22 */ MERGE /*+ INDEX( %TABLENAME_UQF% %TABLENAME_UQF%_PK ) */ INTO %TABLENAME% STATE USING (SELECT * FROM (  " +
					"SELECT STRIPE_INDEX, ASSET_KEY, SITE_ID, ASSET_SITE_ID, OWNER_SITE_ID, TOPIC_ID, CREATE_TM, " +
					"ASSET_VERSION, ASSET_VECTOR, ASSET_DELETE_IND, ASSET_BUCKET, ASSET_TYPE_IND, ASSET_PATH, " +
					"ASSET_SEQ_NUM, ASSET_TOTAL_PARTS, ASSET_PART_SIZE, ROW_NUMBER() OVER (PARTITION BY STRIPE_INDEX, ASSET_KEY, " +
					"ASSET_BUCKET ORDER BY CREATE_TM DESC) DUP FROM %TABLENAME% WHERE STRIPE_INDEX= ? AND " +
					"ASSET_BUCKET= ?) WHERE DUP = 1 AND ASSET_DELETE_IND= 0)NEWSTATE ON (( STATE.STRIPE_INDEX " +
					"=NEWSTATE.STRIPE_INDEX AND STATE.ASSET_KEY=NEWSTATE.ASSET_KEY AND STATE.ASSET_BUCKET=NEWSTATE" +
					".ASSET_BUCKET AND STATE.SITE_ID=?)) WHEN MATCHED THEN  UPDATE SET  STATE.ASSET_SITE_ID=NEWSTATE" +
					".ASSET_SITE_ID, STATE.ASSET_VERSION=(NEWSTATE.ASSET_VERSION+?), " +
					"STATE.ASSET_VECTOR=NEWSTATE.ASSET_VECTOR, STATE.ASSET_DELETE_IND= 1, STATE.CREATE_TM=?, " +
					"STATE.EXPIRATION_TM=?, STATE.MIGRATION_TM=? WHERE  STATE.ASSET_VERSION=NEWSTATE.ASSET_VERSION " +
					"WHEN NOT MATCHED THEN  INSERT (  STATE.STRIPE_INDEX, STATE.ASSET_KEY, STATE.SITE_ID, " +
					"STATE.TOPIC_ID, STATE.ASSET_SITE_ID, STATE.OWNER_SITE_ID, STATE.ASSET_VERSION, " +
					"STATE.ASSET_VECTOR, STATE.ASSET_SEQ_NUM, STATE.CREATE_TM, STATE.EXPIRATION_TM, " +
					"STATE.MIGRATION_TM, STATE.ASSET_DELETE_IND, STATE.ASSET_TOTAL_PARTS, STATE.ASSET_LENGTH, " +
					"STATE.ASSET_STORED_LENGTH, STATE.MOUNT_ID, STATE.FS_VERSION, STATE.ASSET_BUCKET, " +
					"STATE.ASSET_PATH, STATE.ASSET_TYPE_IND, STATE.ASSET_PART_SIZE) VALUES (NEWSTATE.STRIPE_INDEX, NEWSTATE.ASSET_KEY, ?, " +
					"NEWSTATE.TOPIC_ID, NEWSTATE.ASSET_SITE_ID, NEWSTATE.OWNER_SITE_ID, NEWSTATE.ASSET_VERSION, " +
					"NEWSTATE.ASSET_VECTOR, NEWSTATE.ASSET_SEQ_NUM,?, ?, ?, 1, 0, 0, 0, -1, -1, " +
					"NEWSTATE.ASSET_BUCKET, NEWSTATE.ASSET_PATH, NEWSTATE.ASSET_TYPE_IND, NEWSTATE.ASSET_PART_SIZE)";

	String QUERY_UPDATE_FINAL_STATE_DELETE_ALL_PART_WITH_DEPTH =
			" /* HA_QRY_23 */ MERGE /*+ INDEX( %TABLENAME_UQF% %TABLENAME_UQF%_PK) */ INTO %TABLENAME% STATE USING (SELECT * FROM (  " +
					"SELECT STRIPE_INDEX, ASSET_KEY, SITE_ID, ASSET_SITE_ID, OWNER_SITE_ID, TOPIC_ID, CREATE_TM, " +
					"ASSET_VERSION, ASSET_VECTOR, ASSET_DELETE_IND, ASSET_BUCKET, ASSET_TYPE_IND, ASSET_PATH, " +
					"ASSET_SEQ_NUM, ASSET_TOTAL_PARTS, ASSET_PART_SIZE, ROW_NUMBER() OVER (PARTITION BY STRIPE_INDEX, ASSET_KEY, " +
					"ASSET_BUCKET ORDER BY CREATE_TM DESC) DUP FROM %TABLENAME% WHERE STRIPE_INDEX= ? AND " +
					"ASSET_BUCKET= ? AND TAG_%DEPTH% = ?) WHERE DUP = 1 AND ASSET_DELETE_IND= 0)NEWSTATE ON (( STATE" +
					".STRIPE_INDEX =NEWSTATE.STRIPE_INDEX AND STATE.ASSET_KEY=NEWSTATE.ASSET_KEY AND STATE" +
					".ASSET_BUCKET=NEWSTATE.ASSET_BUCKET AND STATE.SITE_ID=?)) WHEN MATCHED THEN  UPDATE SET  STATE" +
					".ASSET_SITE_ID=NEWSTATE.ASSET_SITE_ID, STATE.ASSET_VERSION=(NEWSTATE.ASSET_VERSION+?), " +
					"STATE.ASSET_VECTOR=NEWSTATE.ASSET_VECTOR, STATE.ASSET_DELETE_IND= 1, STATE.CREATE_TM=?, " +
					"STATE.EXPIRATION_TM=?, STATE.MIGRATION_TM=? WHERE  STATE.ASSET_VERSION=NEWSTATE.ASSET_VERSION " +
					"WHEN NOT MATCHED THEN  INSERT (STATE.STRIPE_INDEX, STATE.ASSET_KEY, STATE.SITE_ID, " +
					"STATE.TOPIC_ID, STATE.ASSET_SITE_ID, STATE.OWNER_SITE_ID, STATE.ASSET_VERSION, " +
					"STATE.ASSET_VECTOR, STATE.ASSET_SEQ_NUM, STATE.CREATE_TM, STATE.EXPIRATION_TM, " +
					"STATE.MIGRATION_TM, STATE.ASSET_DELETE_IND, STATE.ASSET_TOTAL_PARTS, STATE.ASSET_LENGTH, " +
					"STATE.ASSET_STORED_LENGTH, STATE.MOUNT_ID, STATE.FS_VERSION, STATE.ASSET_BUCKET, " +
					"STATE.ASSET_PATH, STATE.ASSET_TYPE_IND, STATE.ASSET_PART_SIZE) VALUES (NEWSTATE.STRIPE_INDEX, NEWSTATE.ASSET_KEY, ?, " +
					"NEWSTATE.TOPIC_ID, NEWSTATE.ASSET_SITE_ID, NEWSTATE.OWNER_SITE_ID, NEWSTATE.ASSET_VERSION, " +
					"NEWSTATE.ASSET_VECTOR, NEWSTATE.ASSET_SEQ_NUM,?, ?, ?, 1, 0, 0, 0, -1, -1, " +
					"NEWSTATE.ASSET_BUCKET, NEWSTATE.ASSET_PATH, NEWSTATE.ASSET_TYPE_IND, NEWSTATE.ASSET_PART_SIZE)";

	String QUERY_UPDATE_FINAL_STATE_METADATA_PART_FOLDER_AND_BUCKET =
			" /* HA_QRY_24 */ MERGE /*+ INDEX( %TABLENAME_UQF% %TABLENAME_UQF%_PK ) */ INTO %TABLENAME% STATE USING (SELECT  ? " +
					"STRIPE_INDEX, ? ASSET_KEY, ? SITE_ID, ? TOPIC_ID, ? ASSET_SITE_ID, ? OWNER_SITE_ID, ? CREATE_TM," +
					" ? EXPIRATION_TM, ? MIGRATION_TM, ? ASSET_VERSION, ? ASSET_OLD_VERSION, ? ASSET_SEQ_NUM, " +
					"? ASSET_VECTOR, ? ASSET_TOTAL_PARTS, ? ASSET_LENGTH, ? ASSET_STORED_LENGTH, ? ASSET_DELETE_IND, " +
					"? MOUNT_ID, ? FS_VERSION, ? ASSET_BUCKET, ? ASSET_PATH, ? ASSET_TYPE_IND, " +
					"? ASSET_METADATA FROM DUAL) NEWSTATE ON (( STATE.STRIPE_INDEX =NEWSTATE.STRIPE_INDEX AND STATE" +
					".ASSET_KEY=NEWSTATE.ASSET_KEY AND STATE.ASSET_BUCKET=NEWSTATE.ASSET_BUCKET AND STATE" +
					".SITE_ID=NEWSTATE.SITE_ID)) WHEN MATCHED THEN  UPDATE SET  STATE.ASSET_SITE_ID=NEWSTATE" +
					".ASSET_SITE_ID, STATE.ASSET_VERSION=NEWSTATE.ASSET_VERSION, " +
					"STATE.ASSET_VECTOR=NEWSTATE.ASSET_VECTOR, STATE.CREATE_TM=NEWSTATE.CREATE_TM, " +
					"STATE.EXPIRATION_TM=NEWSTATE.EXPIRATION_TM, STATE.MIGRATION_TM=NEWSTATE.MIGRATION_TM, " +
					"STATE.ASSET_DELETE_IND=NEWSTATE.ASSET_DELETE_IND, STATE.MOUNT_ID=NEWSTATE.MOUNT_ID, " +
					"STATE.FS_VERSION=NEWSTATE.FS_VERSION, STATE.ASSET_PATH=NEWSTATE.ASSET_PATH, " +
					"STATE.ASSET_TYPE_IND=NEWSTATE.ASSET_TYPE_IND, STATE.ASSET_METADATA=NEWSTATE.ASSET_METADATA WHERE" +
					"  STATE.ASSET_VERSION=NEWSTATE.ASSET_OLD_VERSION WHEN NOT MATCHED THEN  INSERT (  STATE" +
					".STRIPE_INDEX, STATE.ASSET_KEY, STATE.SITE_ID, STATE.TOPIC_ID, STATE.ASSET_SITE_ID, " +
					"STATE.OWNER_SITE_ID, STATE.ASSET_VERSION, STATE.ASSET_VECTOR, STATE.ASSET_SEQ_NUM, " +
					"STATE.CREATE_TM, STATE.EXPIRATION_TM, STATE.MIGRATION_TM, STATE.ASSET_TOTAL_PARTS, " +
					"STATE.ASSET_LENGTH, STATE.ASSET_STORED_LENGTH, STATE.ASSET_DELETE_IND, STATE.MOUNT_ID, " +
					"STATE.FS_VERSION, STATE.ASSET_BUCKET, STATE.ASSET_PATH, STATE.ASSET_TYPE_IND, " +
					"STATE.ASSET_METADATA ) VALUES ( NEWSTATE.STRIPE_INDEX, NEWSTATE.ASSET_KEY, NEWSTATE.SITE_ID, " +
					"NEWSTATE.TOPIC_ID, NEWSTATE.ASSET_SITE_ID, NEWSTATE.OWNER_SITE_ID, NEWSTATE.ASSET_VERSION, " +
					"NEWSTATE.ASSET_VECTOR, NEWSTATE.ASSET_SEQ_NUM, NEWSTATE.CREATE_TM, NEWSTATE.EXPIRATION_TM, " +
					"NEWSTATE.MIGRATION_TM, NEWSTATE.ASSET_TOTAL_PARTS, NEWSTATE.ASSET_LENGTH, " +
					"NEWSTATE.ASSET_STORED_LENGTH, NEWSTATE.ASSET_DELETE_IND, NEWSTATE.MOUNT_ID, NEWSTATE.FS_VERSION," +
					" NEWSTATE.ASSET_BUCKET, NEWSTATE.ASSET_PATH, NEWSTATE.ASSET_TYPE_IND, NEWSTATE.ASSET_METADATA)";

	String QUERY_UPDATE_FINAL_STATE_METADATA_PART_FILE =
			" /* HA_QRY_25 */ MERGE /*+ INDEX( %TABLENAME_UQF% %TABLENAME_UQF%_PK ) */ INTO %TABLENAME% STATE USING (SELECT  ? " +
					"STRIPE_INDEX, ? ASSET_KEY, ? SITE_ID, ? TOPIC_ID, ? ASSET_SITE_ID, ? OWNER_SITE_ID, ? CREATE_TM," +
					" ? EXPIRATION_TM, ? MIGRATION_TM, ? ASSET_VERSION, ? ASSET_OLD_VERSION, ? ASSET_SEQ_NUM, " +
					"? ASSET_VECTOR, ? ASSET_TOTAL_PARTS, ? ASSET_LENGTH, ? ASSET_STORED_LENGTH, ? ASSET_DELETE_IND, " +
					"? MOUNT_ID, ? FS_VERSION, ? ASSET_BUCKET, ? ASSET_PATH, ? ASSET_TYPE_IND, " +
					"? ASSET_METADATA FROM DUAL) NEWSTATE ON (( STATE.STRIPE_INDEX =NEWSTATE.STRIPE_INDEX AND STATE" +
					".ASSET_KEY=NEWSTATE.ASSET_KEY AND STATE.ASSET_BUCKET=NEWSTATE.ASSET_BUCKET AND STATE" +
					".SITE_ID=NEWSTATE.SITE_ID)) WHEN MATCHED THEN  UPDATE SET  STATE.ASSET_SITE_ID=NEWSTATE" +
					".ASSET_SITE_ID, STATE.ASSET_VERSION=NEWSTATE.ASSET_VERSION, " +
					"STATE.ASSET_VECTOR=NEWSTATE.ASSET_VECTOR, STATE.ASSET_DELETE_IND=NEWSTATE.ASSET_DELETE_IND, " +
					"STATE.MOUNT_ID=NEWSTATE.MOUNT_ID, STATE.FS_VERSION=NEWSTATE.FS_VERSION, " +
					"STATE.ASSET_PATH=NEWSTATE.ASSET_PATH, STATE.ASSET_TYPE_IND=NEWSTATE.ASSET_TYPE_IND, " +
					"STATE.ASSET_METADATA=NEWSTATE.ASSET_METADATA WHERE  STATE.ASSET_VERSION=NEWSTATE" +
					".ASSET_OLD_VERSION WHEN NOT MATCHED THEN  INSERT (  STATE.STRIPE_INDEX, STATE.ASSET_KEY, " +
					"STATE.SITE_ID, STATE.TOPIC_ID, STATE.ASSET_SITE_ID, STATE.OWNER_SITE_ID, STATE.ASSET_VERSION, " +
					"STATE.ASSET_VECTOR, STATE.ASSET_SEQ_NUM, STATE.CREATE_TM, STATE.EXPIRATION_TM, " +
					"STATE.MIGRATION_TM, STATE.ASSET_TOTAL_PARTS, STATE.ASSET_LENGTH, STATE.ASSET_STORED_LENGTH, " +
					"STATE.ASSET_DELETE_IND, STATE.MOUNT_ID, STATE.FS_VERSION, STATE.ASSET_BUCKET, STATE.ASSET_PATH, " +
					"STATE.ASSET_TYPE_IND, STATE.ASSET_METADATA ) VALUES ( NEWSTATE.STRIPE_INDEX, NEWSTATE.ASSET_KEY," +
					" NEWSTATE.SITE_ID, NEWSTATE.TOPIC_ID, NEWSTATE.ASSET_SITE_ID, NEWSTATE.OWNER_SITE_ID, " +
					"NEWSTATE.ASSET_VERSION, NEWSTATE.ASSET_VECTOR, NEWSTATE.ASSET_SEQ_NUM, NEWSTATE.CREATE_TM, " +
					"NEWSTATE.EXPIRATION_TM, NEWSTATE.MIGRATION_TM, NEWSTATE.ASSET_TOTAL_PARTS, " +
					"NEWSTATE.ASSET_LENGTH, NEWSTATE.ASSET_STORED_LENGTH, NEWSTATE.ASSET_DELETE_IND, " +
					"NEWSTATE.MOUNT_ID, NEWSTATE.FS_VERSION, NEWSTATE.ASSET_BUCKET, NEWSTATE.ASSET_PATH, " +
					"NEWSTATE.ASSET_TYPE_IND, NEWSTATE.ASSET_METADATA)";

	String QUERY_UPDATE_FINAL_STATE_METADATA_PART1_WITH_TAGS_FOLDER_BUCKET =
			" /* HA_QRY_26 */ MERGE /*+ INDEX( %TABLENAME_UQF% %TABLENAME_UQF%_PK ) */ INTO %TABLENAME% STATE USING (SELECT  ? " +
					"STRIPE_INDEX, ? ASSET_KEY, ? SITE_ID, ? TOPIC_ID, ? ASSET_SITE_ID, ? OWNER_SITE_ID, ? CREATE_TM," +
					" ? EXPIRATION_TM, ? MIGRATION_TM, ? ASSET_VERSION, ? ASSET_OLD_VERSION, ? ASSET_SEQ_NUM, " +
					"? ASSET_VECTOR, ? ASSET_TOTAL_PARTS, ? ASSET_LENGTH, ? ASSET_STORED_LENGTH, ? ASSET_DELETE_IND, " +
					"? MOUNT_ID, ? FS_VERSION, ? ASSET_BUCKET, ? ASSET_PATH, ? ASSET_TYPE_IND, ? TAG_1, ? TAG_2, " +
					"? TAG_3, ? TAG_4, ? TAG_5, ? TAG_6, ? TAG_7, ? TAG_8, ? TAG_9, ? TAG_10, ? TAG_11, ? TAG_12, " +
					"? TAG_13, ? TAG_14, ? TAG_15, ? TAG_16, ? TAG_17, ? TAG_18, ? TAG_19, ? TAG_20, ? TAG_21, " +
					"? TAG_22, ? TAG_23, ? TAG_24, ? TAG_25, ? TAG_26, ? TAG_27, ? TAG_28, ? TAG_29, ? TAG_30, " +
					"? TAG_31, ? TAG_32, ? ASSET_METADATA FROM DUAL) NEWSTATE ON (( STATE.STRIPE_INDEX =NEWSTATE" +
					".STRIPE_INDEX AND STATE.ASSET_KEY=NEWSTATE.ASSET_KEY AND STATE.ASSET_BUCKET=NEWSTATE" +
					".ASSET_BUCKET AND STATE.SITE_ID=NEWSTATE.SITE_ID)) WHEN MATCHED THEN  UPDATE SET  STATE" +
					".ASSET_SITE_ID=NEWSTATE.ASSET_SITE_ID, STATE.ASSET_VERSION=NEWSTATE.ASSET_VERSION, " +
					"STATE.ASSET_VECTOR=NEWSTATE.ASSET_VECTOR, STATE.CREATE_TM=NEWSTATE.CREATE_TM, " +
					"STATE.EXPIRATION_TM=NEWSTATE.EXPIRATION_TM, STATE.MIGRATION_TM=NEWSTATE.MIGRATION_TM, " +
					"STATE.ASSET_DELETE_IND=NEWSTATE.ASSET_DELETE_IND, STATE.MOUNT_ID=NEWSTATE.MOUNT_ID, " +
					"STATE.FS_VERSION=NEWSTATE.FS_VERSION, STATE.ASSET_PATH=NEWSTATE.ASSET_PATH, " +
					"STATE.ASSET_TYPE_IND=NEWSTATE.ASSET_TYPE_IND, STATE.TAG_1=NEWSTATE.TAG_1, " +
					"STATE.TAG_2=NEWSTATE.TAG_2, STATE.TAG_3=NEWSTATE.TAG_3, STATE.TAG_4=NEWSTATE.TAG_4, " +
					"STATE.TAG_5=NEWSTATE.TAG_5, STATE.TAG_6=NEWSTATE.TAG_6, STATE.TAG_7=NEWSTATE.TAG_7, " +
					"STATE.TAG_8=NEWSTATE.TAG_8, STATE.TAG_9=NEWSTATE.TAG_9, STATE.TAG_10=NEWSTATE.TAG_10, " +
					"STATE.TAG_11=NEWSTATE.TAG_11, STATE.TAG_12=NEWSTATE.TAG_12, STATE.TAG_13=NEWSTATE.TAG_13, " +
					"STATE.TAG_14=NEWSTATE.TAG_14, STATE.TAG_15=NEWSTATE.TAG_15, STATE.TAG_16=NEWSTATE.TAG_16, " +
					"STATE.TAG_17=NEWSTATE.TAG_17, STATE.TAG_18=NEWSTATE.TAG_18, STATE.TAG_19=NEWSTATE.TAG_19, " +
					"STATE.TAG_20=NEWSTATE.TAG_20, STATE.TAG_21=NEWSTATE.TAG_21, STATE.TAG_22=NEWSTATE.TAG_22, " +
					"STATE.TAG_23=NEWSTATE.TAG_23, STATE.TAG_24=NEWSTATE.TAG_24, STATE.TAG_25=NEWSTATE.TAG_25, " +
					"STATE.TAG_26=NEWSTATE.TAG_26, STATE.TAG_27=NEWSTATE.TAG_27, STATE.TAG_28=NEWSTATE.TAG_28, " +
					"STATE.TAG_29=NEWSTATE.TAG_29, STATE.TAG_30=NEWSTATE.TAG_30, STATE.TAG_31=NEWSTATE.TAG_31, " +
					"STATE.TAG_32=NEWSTATE.TAG_32, STATE.ASSET_METADATA=NEWSTATE.ASSET_METADATA WHERE  STATE" +
					".ASSET_VERSION=NEWSTATE.ASSET_OLD_VERSION WHEN NOT MATCHED THEN  INSERT (  STATE.STRIPE_INDEX, " +
					"STATE.ASSET_KEY, STATE.SITE_ID, STATE.TOPIC_ID, STATE.ASSET_SITE_ID, STATE.OWNER_SITE_ID, " +
					"STATE.ASSET_VERSION, STATE.ASSET_VECTOR, STATE.ASSET_SEQ_NUM, STATE.CREATE_TM, " +
					"STATE.EXPIRATION_TM, STATE.MIGRATION_TM, STATE.ASSET_TOTAL_PARTS, STATE.ASSET_LENGTH, " +
					"STATE.ASSET_STORED_LENGTH, STATE.ASSET_DELETE_IND, STATE.MOUNT_ID, STATE.FS_VERSION, " +
					"STATE.ASSET_BUCKET, STATE.ASSET_PATH, STATE.ASSET_TYPE_IND, STATE.TAG_1 , STATE.TAG_2 , " +
					"STATE.TAG_3 , STATE.TAG_4 , STATE.TAG_5 , STATE.TAG_6 , STATE.TAG_7 , STATE.TAG_8 , " +
					"STATE.TAG_9 , STATE.TAG_10, STATE.TAG_11, STATE.TAG_12, STATE.TAG_13, STATE.TAG_14, " +
					"STATE.TAG_15, STATE.TAG_16, STATE.TAG_17, STATE.TAG_18, STATE.TAG_19, STATE.TAG_20, " +
					"STATE.TAG_21, STATE.TAG_22, STATE.TAG_23, STATE.TAG_24, STATE.TAG_25, STATE.TAG_26, " +
					"STATE.TAG_27, STATE.TAG_28, STATE.TAG_29, STATE.TAG_30, STATE.TAG_31, STATE.TAG_32, " +
					"STATE.ASSET_METADATA ) VALUES ( NEWSTATE.STRIPE_INDEX, NEWSTATE.ASSET_KEY, NEWSTATE.SITE_ID, " +
					"NEWSTATE.TOPIC_ID, NEWSTATE.ASSET_SITE_ID, NEWSTATE.OWNER_SITE_ID, NEWSTATE.ASSET_VERSION, " +
					"NEWSTATE.ASSET_VECTOR, NEWSTATE.ASSET_SEQ_NUM, NEWSTATE.CREATE_TM, NEWSTATE.EXPIRATION_TM, " +
					"NEWSTATE.MIGRATION_TM, NEWSTATE.ASSET_TOTAL_PARTS, NEWSTATE.ASSET_LENGTH, " +
					"NEWSTATE.ASSET_STORED_LENGTH, NEWSTATE.ASSET_DELETE_IND, NEWSTATE.MOUNT_ID, NEWSTATE.FS_VERSION," +
					" NEWSTATE.ASSET_BUCKET, NEWSTATE.ASSET_PATH, NEWSTATE.ASSET_TYPE_IND, NEWSTATE.TAG_1 , " +
					"NEWSTATE.TAG_2 , NEWSTATE.TAG_3 , NEWSTATE.TAG_4 , NEWSTATE.TAG_5 , NEWSTATE.TAG_6 , " +
					"NEWSTATE.TAG_7 , NEWSTATE.TAG_8 , NEWSTATE.TAG_9 , NEWSTATE.TAG_10, NEWSTATE.TAG_11, " +
					"NEWSTATE.TAG_12, NEWSTATE.TAG_13, NEWSTATE.TAG_14, NEWSTATE.TAG_15, NEWSTATE.TAG_16, " +
					"NEWSTATE.TAG_17, NEWSTATE.TAG_18, NEWSTATE.TAG_19, NEWSTATE.TAG_20, NEWSTATE.TAG_21, " +
					"NEWSTATE.TAG_22, NEWSTATE.TAG_23, NEWSTATE.TAG_24, NEWSTATE.TAG_25, NEWSTATE.TAG_26, " +
					"NEWSTATE.TAG_27, NEWSTATE.TAG_28, NEWSTATE.TAG_29, NEWSTATE.TAG_30, NEWSTATE.TAG_31, " +
					"NEWSTATE.TAG_32, NEWSTATE.ASSET_METADATA)";

	String QUERY_UPDATE_FINAL_STATE_METADATA_PART1_WITH_TAGS_FILE =
			" /* HA_QRY_27 */ MERGE /*+ INDEX( %TABLENAME_UQF% %TABLENAME_UQF%_PK ) */ INTO %TABLENAME% STATE USING (SELECT  ? " +
					"STRIPE_INDEX, ? ASSET_KEY, ? SITE_ID, ? TOPIC_ID, ? ASSET_SITE_ID, ? OWNER_SITE_ID, ? CREATE_TM," +
					" ? EXPIRATION_TM, ? MIGRATION_TM, ? ASSET_VERSION, ? ASSET_OLD_VERSION, ? ASSET_SEQ_NUM, " +
					"? ASSET_VECTOR, ? ASSET_TOTAL_PARTS, ? ASSET_LENGTH, ? ASSET_STORED_LENGTH, ? ASSET_DELETE_IND, " +
					"? MOUNT_ID, ? FS_VERSION, ? ASSET_BUCKET, ? ASSET_PATH, ? ASSET_TYPE_IND, ? TAG_1, ? TAG_2, " +
					"? TAG_3, ? TAG_4, ? TAG_5, ? TAG_6, ? TAG_7, ? TAG_8, ? TAG_9, ? TAG_10, ? TAG_11, ? TAG_12, " +
					"? TAG_13, ? TAG_14, ? TAG_15, ? TAG_16, ? TAG_17, ? TAG_18, ? TAG_19, ? TAG_20, ? TAG_21, " +
					"? TAG_22, ? TAG_23, ? TAG_24, ? TAG_25, ? TAG_26, ? TAG_27, ? TAG_28, ? TAG_29, ? TAG_30, " +
					"? TAG_31, ? TAG_32, ? ASSET_METADATA FROM DUAL) NEWSTATE ON (( STATE.STRIPE_INDEX =NEWSTATE" +
					".STRIPE_INDEX AND STATE.ASSET_KEY=NEWSTATE.ASSET_KEY AND STATE.ASSET_BUCKET=NEWSTATE" +
					".ASSET_BUCKET AND STATE.SITE_ID=NEWSTATE.SITE_ID)) WHEN MATCHED THEN  UPDATE SET  STATE" +
					".ASSET_SITE_ID=NEWSTATE.ASSET_SITE_ID, STATE.ASSET_VERSION=NEWSTATE.ASSET_VERSION, " +
					"STATE.ASSET_VECTOR=NEWSTATE.ASSET_VECTOR, STATE.ASSET_DELETE_IND=NEWSTATE.ASSET_DELETE_IND, " +
					"STATE.MOUNT_ID=NEWSTATE.MOUNT_ID, STATE.FS_VERSION=NEWSTATE.FS_VERSION, " +
					"STATE.ASSET_PATH=NEWSTATE.ASSET_PATH, STATE.ASSET_TYPE_IND=NEWSTATE.ASSET_TYPE_IND, " +
					"STATE.TAG_1=NEWSTATE.TAG_1, STATE.TAG_2=NEWSTATE.TAG_2, STATE.TAG_3=NEWSTATE.TAG_3, " +
					"STATE.TAG_4=NEWSTATE.TAG_4, STATE.TAG_5=NEWSTATE.TAG_5, STATE.TAG_6=NEWSTATE.TAG_6, " +
					"STATE.TAG_7=NEWSTATE.TAG_7, STATE.TAG_8=NEWSTATE.TAG_8, STATE.TAG_9=NEWSTATE.TAG_9, " +
					"STATE.TAG_10=NEWSTATE.TAG_10, STATE.TAG_11=NEWSTATE.TAG_11, STATE.TAG_12=NEWSTATE.TAG_12, " +
					"STATE.TAG_13=NEWSTATE.TAG_13, STATE.TAG_14=NEWSTATE.TAG_14, STATE.TAG_15=NEWSTATE.TAG_15, " +
					"STATE.TAG_16=NEWSTATE.TAG_16, STATE.TAG_17=NEWSTATE.TAG_17, STATE.TAG_18=NEWSTATE.TAG_18, " +
					"STATE.TAG_19=NEWSTATE.TAG_19, STATE.TAG_20=NEWSTATE.TAG_20, STATE.TAG_21=NEWSTATE.TAG_21, " +
					"STATE.TAG_22=NEWSTATE.TAG_22, STATE.TAG_23=NEWSTATE.TAG_23, STATE.TAG_24=NEWSTATE.TAG_24, " +
					"STATE.TAG_25=NEWSTATE.TAG_25, STATE.TAG_26=NEWSTATE.TAG_26, STATE.TAG_27=NEWSTATE.TAG_27, " +
					"STATE.TAG_28=NEWSTATE.TAG_28, STATE.TAG_29=NEWSTATE.TAG_29, STATE.TAG_30=NEWSTATE.TAG_30, " +
					"STATE.TAG_31=NEWSTATE.TAG_31, STATE.TAG_32=NEWSTATE.TAG_32, " +
					"STATE.ASSET_METADATA=NEWSTATE.ASSET_METADATA WHERE  STATE.ASSET_VERSION=NEWSTATE" +
					".ASSET_OLD_VERSION WHEN NOT MATCHED THEN  INSERT (  STATE.STRIPE_INDEX, STATE.ASSET_KEY, " +
					"STATE.SITE_ID, STATE.TOPIC_ID, STATE.ASSET_SITE_ID, STATE.OWNER_SITE_ID, STATE.ASSET_VERSION, " +
					"STATE.ASSET_VECTOR, STATE.ASSET_SEQ_NUM, STATE.CREATE_TM, STATE.EXPIRATION_TM, " +
					"STATE.MIGRATION_TM, STATE.ASSET_TOTAL_PARTS, STATE.ASSET_LENGTH, STATE.ASSET_STORED_LENGTH, " +
					"STATE.ASSET_DELETE_IND, STATE.MOUNT_ID, STATE.FS_VERSION, STATE.ASSET_BUCKET, STATE.ASSET_PATH, " +
					"STATE.ASSET_TYPE_IND, STATE.TAG_1 , STATE.TAG_2 , STATE.TAG_3 , STATE.TAG_4 , STATE.TAG_5 , " +
					"STATE.TAG_6 , STATE.TAG_7 , STATE.TAG_8 , STATE.TAG_9 , STATE.TAG_10, STATE.TAG_11, " +
					"STATE.TAG_12, STATE.TAG_13, STATE.TAG_14, STATE.TAG_15, STATE.TAG_16, STATE.TAG_17, " +
					"STATE.TAG_18, STATE.TAG_19, STATE.TAG_20, STATE.TAG_21, STATE.TAG_22, STATE.TAG_23, " +
					"STATE.TAG_24, STATE.TAG_25, STATE.TAG_26, STATE.TAG_27, STATE.TAG_28, STATE.TAG_29, " +
					"STATE.TAG_30, STATE.TAG_31, STATE.TAG_32, STATE.ASSET_METADATA ) VALUES ( NEWSTATE.STRIPE_INDEX," +
					" NEWSTATE.ASSET_KEY, NEWSTATE.SITE_ID, NEWSTATE.TOPIC_ID, NEWSTATE.ASSET_SITE_ID, " +
					"NEWSTATE.OWNER_SITE_ID, NEWSTATE.ASSET_VERSION, NEWSTATE.ASSET_VECTOR, NEWSTATE.ASSET_SEQ_NUM, " +
					"NEWSTATE.CREATE_TM, NEWSTATE.EXPIRATION_TM, NEWSTATE.MIGRATION_TM, NEWSTATE.ASSET_TOTAL_PARTS, " +
					"NEWSTATE.ASSET_LENGTH, NEWSTATE.ASSET_STORED_LENGTH, NEWSTATE.ASSET_DELETE_IND, " +
					"NEWSTATE.MOUNT_ID, NEWSTATE.FS_VERSION, NEWSTATE.ASSET_BUCKET, NEWSTATE.ASSET_PATH, " +
					"NEWSTATE.ASSET_TYPE_IND, NEWSTATE.TAG_1 , NEWSTATE.TAG_2 , NEWSTATE.TAG_3 , NEWSTATE.TAG_4 , " +
					"NEWSTATE.TAG_5 , NEWSTATE.TAG_6 , NEWSTATE.TAG_7 , NEWSTATE.TAG_8 , NEWSTATE.TAG_9 , " +
					"NEWSTATE.TAG_10, NEWSTATE.TAG_11, NEWSTATE.TAG_12, NEWSTATE.TAG_13, NEWSTATE.TAG_14, " +
					"NEWSTATE.TAG_15, NEWSTATE.TAG_16, NEWSTATE.TAG_17, NEWSTATE.TAG_18, NEWSTATE.TAG_19, " +
					"NEWSTATE.TAG_20, NEWSTATE.TAG_21, NEWSTATE.TAG_22, NEWSTATE.TAG_23, NEWSTATE.TAG_24, " +
					"NEWSTATE.TAG_25, NEWSTATE.TAG_26, NEWSTATE.TAG_27, NEWSTATE.TAG_28, NEWSTATE.TAG_29, " +
					"NEWSTATE.TAG_30, NEWSTATE.TAG_31, NEWSTATE.TAG_32, NEWSTATE.ASSET_METADATA)";

	String QUERY_COPY_PAYLOAD_SELECT_WITH_RETENTION = " /* HA_QRY_28 */ SELECT /*+ INDEX(%TABLENAME_UQF% %TABLENAME_UQF%_PK) */ * FROM %TABLENAME% WHERE STRIPE_INDEX=? AND "
			+ "ASSET_KEY=? AND SITE_ID=? AND ASSET_BUCKET=? AND ASSET_PART_NUM=? AND ASSET_VERSION=? AND CREATE_TM=? ";

	String QUERY_COPY_PAYLOAD_INSERT_COLUMNS_PART_ONE =
			" /* HA_QRY_29 */ INSERT INTO %TABLENAME_DST% (STRIPE_INDEX, ASSET_KEY, SITE_ID, TOPIC_ID, CREATE_TM, MIGRATION_TM, " +
					"EXPIRATION_TM, ASSET_PAYLOAD, ASSET_DATA, ASSET_PART_NUM, ASSET_BUCKET, " +
					"ASSET_VERSION) VALUES (?,?,?,?,?,?,?,?,?,?,?,%TABLENAME_DST%_SEQ.nextVal) RETURNING " +
					"ASSET_VERSION INTO ?";

	String QUERY_COPY_PAYLOAD_INSERT_COLUMNS =
			" /* HA_QRY_30 */ INSERT INTO %TABLENAME_DST% (STRIPE_INDEX, ASSET_KEY, SITE_ID, TOPIC_ID, CREATE_TM, MIGRATION_TM, " +
					"EXPIRATION_TM, ASSET_PAYLOAD, ASSET_DATA, ASSET_PART_NUM, ASSET_BUCKET, " +
					"ASSET_VERSION) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)";

	String QUERY_COPY_PAYLOAD_SELECT_INSERT_COLUMNS_PART_ONE = " /* HA_QRY_31 */ INSERT INTO %TABLENAME_DST% "
			+ "(STRIPE_INDEX, ASSET_KEY, SITE_ID, TOPIC_ID, CREATE_TM, MIGRATION_TM, EXPIRATION_TM, ASSET_PAYLOAD, ASSET_DATA, ASSET_PART_NUM, ASSET_BUCKET, ASSET_VERSION) "
			+ "SELECT /*+ INDEX(%TABLENAME_UQF% %TABLENAME_UQF%_PK) */ ? , ?, ?, TOPIC_ID, ?, ?, EXPIRATION_TM, ASSET_PAYLOAD, ASSET_DATA, ASSET_PART_NUM, ?, %TABLENAME_DST%_SEQ.nextVal"
			+ " FROM %TABLENAME% WHERE STRIPE_INDEX=? AND ASSET_KEY=? AND SITE_ID=? AND ASSET_BUCKET=? AND ASSET_PART_NUM=? AND ASSET_VERSION=? AND CREATE_TM=? RETURNING " + "ASSET_VERSION INTO ?";

	String QUERY_COPY_PAYLOAD_SELECT_INSERT_COLUMNS = " /* HA_QRY_32 */ INSERT INTO %TABLENAME_DST% "
			+ "(STRIPE_INDEX, ASSET_KEY, SITE_ID, TOPIC_ID, CREATE_TM, MIGRATION_TM, EXPIRATION_TM, ASSET_PAYLOAD, ASSET_DATA, ASSET_PART_NUM, ASSET_BUCKET, ASSET_VERSION) "
			+ "SELECT /*+ INDEX(%TABLENAME_UQF% %TABLENAME_UQF%_PK) */ ? , ?, ?, TOPIC_ID, ?, ?, EXPIRATION_TM, ASSET_PAYLOAD, ASSET_DATA, ASSET_PART_NUM, ?, ?"
			+ " FROM %TABLENAME% WHERE STRIPE_INDEX=? AND ASSET_KEY=? AND SITE_ID=? AND ASSET_BUCKET=? AND ASSET_VERSION=? AND CREATE_TM=?";
	
	String QUERY_GET_PAYLOAD_PARTS =
			" /* HA_QRY_33 */ SELECT /*+ INDEX(%TABLENAME_UQF% %TABLENAME_UQF%_PK) */ ASSET_PAYLOAD, ASSET_DATA, " +
					"ASSET_PART_NUM FROM %TABLENAME% WHERE STRIPE_INDEX=? AND SITE_ID=? AND ASSET_VERSION=? AND " +
					"ASSET_KEY=? AND ASSET_BUCKET=? AND ASSET_PART_NUM=? AND CREATE_TM=? AND TOPIC_ID=?";

	String UPDATE_ASSET_TEMP_STATE =
			" /* HA_QRY_34 */ MERGE /*+ INDEX(%TABLENAME_UQF% %TABLENAME_UQF%_PK) */ INTO %TABLENAME% STATE USING (SELECT ? " +
					"STRIPE_INDEX, ? ASSET_KEY,? ASSET_BUCKET,? ASSET_PATH,? ASSET_TYPE_IND, ? ASSET_METADATA, " +
					"? SITE_ID, ? TOPIC_ID, ? ASSET_TOTAL_PARTS, ? ASSET_PART_SIZE, ? ASSET_STORED_PARTS, ? ASSET_STORED_LENGTH, " +
					"? ASSET_TOTAL_LENGTH, ? ASSET_SEQ_NUM, ? ASSET_VERSION, ? ASSET_TTL_VALUE, ? CREATE_TM, ? TAG_1," +
					" ? TAG_2, ? TAG_3, ? TAG_4, ? TAG_5, ? TAG_6, ? TAG_7, ? TAG_8, ? TAG_9, ? TAG_10, ? TAG_11, " +
					"? TAG_12, ? TAG_13, ? TAG_14, ? TAG_15, ? TAG_16, ? TAG_17, ? TAG_18, ? TAG_19, ? TAG_20, " +
					"? TAG_21, ? TAG_22, ? TAG_23, ? TAG_24, ? TAG_25, ? TAG_26, ? TAG_27, ? TAG_28, ? TAG_29, " +
					"? TAG_30, ? TAG_31, ? TAG_32 FROM DUAL) NEWSTATE ON ( STATE.STRIPE_INDEX=NEWSTATE.STRIPE_INDEX " +
					"AND STATE.ASSET_KEY=NEWSTATE.ASSET_KEY AND STATE.ASSET_BUCKET=NEWSTATE.ASSET_BUCKET AND STATE" +
					".SITE_ID=NEWSTATE.SITE_ID AND STATE.TOPIC_ID=NEWSTATE.TOPIC_ID ) WHEN MATCHED THEN UPDATE SET " +
					"STATE.ASSET_TOTAL_PARTS=NEWSTATE.ASSET_TOTAL_PARTS, STATE.ASSET_PART_SIZE=NEWSTATE.ASSET_PART_SIZE, STATE.ASSET_STORED_LENGTH=NEWSTATE" +
					".ASSET_STORED_LENGTH, STATE.ASSET_STORED_PARTS=NEWSTATE.ASSET_STORED_PARTS, STATE.CREATE_TM=NEWSTATE.CREATE_TM, STATE.ASSET_SEQ_NUM=NEWSTATE.ASSET_SEQ_NUM WHERE (STATE.ASSET_STORED_PARTS=" +
					"(NEWSTATE.ASSET_STORED_PARTS-1) OR NEWSTATE.ASSET_STORED_PARTS=1) WHEN NOT MATCHED THEN INSERT (" +
					" STATE.STRIPE_INDEX, STATE.ASSET_KEY, STATE.ASSET_BUCKET, STATE.ASSET_PATH, " +
					"STATE.ASSET_TYPE_IND, STATE.ASSET_METADATA, STATE.SITE_ID, STATE.TOPIC_ID, " +
					"STATE.ASSET_TOTAL_PARTS, STATE.ASSET_PART_SIZE, STATE.ASSET_STORED_PARTS, STATE.ASSET_STORED_LENGTH, " +
					"STATE.ASSET_TOTAL_LENGTH, STATE.ASSET_SEQ_NUM, STATE.ASSET_VERSION, STATE.ASSET_TTL_VALUE, " +
					"STATE.CREATE_TM, STATE.TAG_1, STATE.TAG_2, STATE.TAG_3, STATE.TAG_4, STATE.TAG_5, STATE.TAG_6, " +
					"STATE.TAG_7, STATE.TAG_8, STATE.TAG_9, STATE.TAG_10, STATE.TAG_11, STATE.TAG_12, STATE.TAG_13, " +
					"STATE.TAG_14, STATE.TAG_15, STATE.TAG_16, STATE.TAG_17, STATE.TAG_18, STATE.TAG_19, " +
					"STATE.TAG_20, STATE.TAG_21, STATE.TAG_22, STATE.TAG_23, STATE.TAG_24, STATE.TAG_25, " +
					"STATE.TAG_26, STATE.TAG_27, STATE.TAG_28, STATE.TAG_29, STATE.TAG_30, STATE.TAG_31, " +
					"STATE.TAG_32) VALUES ( NEWSTATE.STRIPE_INDEX, NEWSTATE.ASSET_KEY, NEWSTATE.ASSET_BUCKET, " +
					"NEWSTATE.ASSET_PATH, NEWSTATE.ASSET_TYPE_IND, NEWSTATE.ASSET_METADATA, NEWSTATE.SITE_ID, " +
					"NEWSTATE.TOPIC_ID, NEWSTATE.ASSET_TOTAL_PARTS, NEWSTATE.ASSET_PART_SIZE, NEWSTATE.ASSET_STORED_PARTS, " +
					"NEWSTATE.ASSET_STORED_LENGTH, NEWSTATE.ASSET_TOTAL_LENGTH, NEWSTATE.ASSET_SEQ_NUM, " +
					"NEWSTATE.ASSET_VERSION, NEWSTATE.ASSET_TTL_VALUE, NEWSTATE.CREATE_TM, NEWSTATE.TAG_1, " +
					"NEWSTATE.TAG_2, NEWSTATE.TAG_3, NEWSTATE.TAG_4, NEWSTATE.TAG_5, NEWSTATE.TAG_6, NEWSTATE.TAG_7, " +
					"NEWSTATE.TAG_8, NEWSTATE.TAG_9, NEWSTATE.TAG_10, NEWSTATE.TAG_11, NEWSTATE.TAG_12, " +
					"NEWSTATE.TAG_13, NEWSTATE.TAG_14, NEWSTATE.TAG_15, NEWSTATE.TAG_16, NEWSTATE.TAG_17, " +
					"NEWSTATE.TAG_18, NEWSTATE.TAG_19, NEWSTATE.TAG_20, NEWSTATE.TAG_21, NEWSTATE.TAG_22, " +
					"NEWSTATE.TAG_23, NEWSTATE.TAG_24, NEWSTATE.TAG_25, NEWSTATE.TAG_26, NEWSTATE.TAG_27, " +
					"NEWSTATE.TAG_28, NEWSTATE.TAG_29, NEWSTATE.TAG_30, NEWSTATE.TAG_31, NEWSTATE.TAG_32)";

	String QUERY_INSERT_ASSET_PAYLOAD_PARTS =
			" /* HA_QRY_35 */ INSERT INTO %TABLENAME% (STRIPE_INDEX, ASSET_KEY, ASSET_BUCKET, SITE_ID, TOPIC_ID, ASSET_PAYLOAD, " +
					"ASSET_DATA, CREATE_TM, MIGRATION_TM, EXPIRATION_TM, ASSET_PART_NUM, ASSET_VERSION) " +
					"VALUES (?,?,?,?,?,?,?,?,?,?,?,?)";

	String QUERY_INSERT_ASSET_PAYLOAD_PART_ONE =
			" /* HA_QRY_36 */ INSERT INTO %TABLENAME% (STRIPE_INDEX, ASSET_KEY, ASSET_BUCKET, SITE_ID, TOPIC_ID, ASSET_PAYLOAD, " +
					"ASSET_DATA, CREATE_TM, MIGRATION_TM, EXPIRATION_TM, ASSET_PART_NUM, ASSET_VERSION) " +
					"VALUES (?,?,?,?,?,?,?,?,?,?,?,%TABLENAME%_SEQ.nextVal) RETURNING ASSET_VERSION INTO ?";

	String QUERY_DELETE_ASSET_PAYLOAD_PARTS =
			" /* HA_QRY_37 */ DELETE /*+ INDEX(%TABLENAME_UQF% %TABLENAME_UQF%_PK) */ FROM %TABLENAME% WHERE STRIPE_INDEX=? AND " +
					"SITE_ID=? AND ASSET_VERSION=? " +
					"AND ASSET_KEY=? AND ASSET_BUCKET=? AND ASSET_PART_NUM>? AND TOPIC_ID=?";

	String QUERY_DELETE_ASSET_TEMP_STATE =
			" /* HA_QRY_38 */ DELETE /*+ INDEX(%TABLENAME_UQF% %TABLENAME_UQF%_PK) */ FROM %TABLENAME%  WHERE STRIPE_INDEX=? AND " +
					"ASSET_KEY=? AND ASSET_BUCKET=? AND SITE_ID=? AND TOPIC_ID=?";

	String SET_ASSET_TEMP_STATE =
			" /* HA_QRY_39 */ UPDATE /*+ INDEX(%TABLENAME_UQF% %TABLENAME_UQF%_PK) */ %TABLENAME% SET ASSET_STORED_PARTS=?, " +
					"ASSET_STORED_LENGTH=? WHERE STRIPE_INDEX=? AND " +
					"ASSET_KEY=? AND ASSET_BUCKET=? AND SITE_ID=? AND TOPIC_ID=?";

	String UPDATE_ASSET_FINAL_STATE =
			" /* HA_QRY_40 */ MERGE /*+ INDEX(%TABLENAME_UQF% %TABLENAME_UQF%_PK) */ INTO %TABLENAME% STATE USING (SELECT ? " +
					"STRIPE_INDEX, ? ASSET_KEY, ? ASSET_BUCKET,? ASSET_PATH, ? ASSET_TYPE_IND, ? ASSET_METADATA, " +
					"? SITE_ID, ? TOPIC_ID, ? ASSET_SITE_ID, ? OWNER_SITE_ID, ? CREATE_TM, ? EXPIRATION_TM, " +
					"? MIGRATION_TM, ? ASSET_VERSION, ? ASSET_OLD_VERSION, ? ASSET_SEQ_NUM, ? ASSET_VECTOR, " +
					"? ASSET_TOTAL_PARTS, ? ASSET_PART_SIZE, ? ASSET_LENGTH, ? ASSET_STORED_LENGTH, ? ASSET_TYPE, ? ASSET_CHECKSUM, " +
					"? ASSET_DELETE_IND, ? MOUNT_ID, ? VIRUS_SCAN_STATUS, ? VIRUS_SCAN_DEFN, ? VIRUS_SCAN_DEFN_TM, " +
					"? VIRUS_SCAN_TM, ? FS_VERSION, ? MOUNT_FILE_PATH, ? TAG_1, ? TAG_2, ? TAG_3, ? TAG_4, ? TAG_5, " +
					"? TAG_6, ? TAG_7, ? TAG_8, ? TAG_9, ? TAG_10, ? TAG_11, ? TAG_12, ? TAG_13, ? TAG_14, ? TAG_15, " +
					"? TAG_16, ? TAG_17, ? TAG_18, ? TAG_19, ? TAG_20, ? TAG_21, ? TAG_22, ? TAG_23, ? TAG_24, " +
					"? TAG_25, ? TAG_26, ? TAG_27, ? TAG_28, ? TAG_29, ? TAG_30, ? TAG_31, " +
					"? TAG_32 FROM DUAL) NEWSTATE ON ( STATE.STRIPE_INDEX=NEWSTATE.STRIPE_INDEX AND STATE" +
					".ASSET_KEY=NEWSTATE.ASSET_KEY AND STATE.SITE_ID=NEWSTATE.SITE_ID AND STATE.ASSET_BUCKET=NEWSTATE" +
					".ASSET_BUCKET) WHEN MATCHED THEN UPDATE SET STATE.ASSET_SITE_ID=NEWSTATE.ASSET_SITE_ID, " +
					"STATE.ASSET_VERSION=NEWSTATE.ASSET_VERSION, STATE.ASSET_VECTOR=NEWSTATE.ASSET_VECTOR, " +
					"STATE.ASSET_SEQ_NUM=NEWSTATE.ASSET_SEQ_NUM, STATE.CREATE_TM=NEWSTATE.CREATE_TM, " +
					"STATE.EXPIRATION_TM=NEWSTATE.EXPIRATION_TM, STATE.MIGRATION_TM=NEWSTATE.MIGRATION_TM, " +
					"STATE.ASSET_TOTAL_PARTS=NEWSTATE.ASSET_TOTAL_PARTS, STATE.ASSET_PART_SIZE=NEWSTATE.ASSET_PART_SIZE, STATE.ASSET_LENGTH=NEWSTATE.ASSET_LENGTH, " +
					"STATE.ASSET_STORED_LENGTH=NEWSTATE.ASSET_STORED_LENGTH, STATE.ASSET_TYPE=NEWSTATE.ASSET_TYPE, " +
					"STATE.ASSET_CHECKSUM=NEWSTATE.ASSET_CHECKSUM, STATE.ASSET_DELETE_IND=NEWSTATE.ASSET_DELETE_IND, " +
					"STATE.MOUNT_ID=NEWSTATE.MOUNT_ID, STATE.VIRUS_SCAN_STATUS=NEWSTATE.VIRUS_SCAN_STATUS, " +
					"STATE.VIRUS_SCAN_DEFN=NEWSTATE.VIRUS_SCAN_DEFN, STATE.VIRUS_SCAN_DEFN_TM=NEWSTATE" +
					".VIRUS_SCAN_DEFN_TM, STATE.VIRUS_SCAN_TM=NEWSTATE.VIRUS_SCAN_TM, " +
					"STATE.FS_VERSION=NEWSTATE.FS_VERSION, STATE.MOUNT_FILE_PATH=NEWSTATE.MOUNT_FILE_PATH, " +
					"STATE.ASSET_PATH=NEWSTATE.ASSET_PATH, STATE.ASSET_TYPE_IND=NEWSTATE.ASSET_TYPE_IND, " +
					"STATE.ASSET_METADATA=NEWSTATE.ASSET_METADATA, STATE.TAG_1=NEWSTATE.TAG_1, " +
					"STATE.TAG_2=NEWSTATE.TAG_2, STATE.TAG_3=NEWSTATE.TAG_3, STATE.TAG_4=NEWSTATE.TAG_4, " +
					"STATE.TAG_5=NEWSTATE.TAG_5, STATE.TAG_6=NEWSTATE.TAG_6, STATE.TAG_7=NEWSTATE.TAG_7, " +
					"STATE.TAG_8=NEWSTATE.TAG_8, STATE.TAG_9=NEWSTATE.TAG_9, STATE.TAG_10=NEWSTATE.TAG_10, " +
					"STATE.TAG_11=NEWSTATE.TAG_11, STATE.TAG_12=NEWSTATE.TAG_12, STATE.TAG_13=NEWSTATE.TAG_13, " +
					"STATE.TAG_14=NEWSTATE.TAG_14, STATE.TAG_15=NEWSTATE.TAG_15, STATE.TAG_16=NEWSTATE.TAG_16, " +
					"STATE.TAG_17=NEWSTATE.TAG_17, STATE.TAG_18=NEWSTATE.TAG_18, STATE.TAG_19=NEWSTATE.TAG_19, " +
					"STATE.TAG_20=NEWSTATE.TAG_20, STATE.TAG_21=NEWSTATE.TAG_21, STATE.TAG_22=NEWSTATE.TAG_22, " +
					"STATE.TAG_23=NEWSTATE.TAG_23, STATE.TAG_24=NEWSTATE.TAG_24, STATE.TAG_25=NEWSTATE.TAG_25, " +
					"STATE.TAG_26=NEWSTATE.TAG_26, STATE.TAG_27=NEWSTATE.TAG_27, STATE.TAG_28=NEWSTATE.TAG_28, " +
					"STATE.TAG_29=NEWSTATE.TAG_29, STATE.TAG_30=NEWSTATE.TAG_30, STATE.TAG_31=NEWSTATE.TAG_31, " +
					"STATE.TAG_32=NEWSTATE.TAG_32 WHERE STATE.ASSET_VERSION=NEWSTATE.ASSET_OLD_VERSION WHEN NOT " +
					"MATCHED THEN INSERT ( STATE.STRIPE_INDEX, STATE.ASSET_KEY, STATE.ASSET_BUCKET, STATE.SITE_ID, " +
					"STATE.TOPIC_ID, STATE.ASSET_SITE_ID, STATE.OWNER_SITE_ID, STATE.ASSET_VERSION, " +
					"STATE.ASSET_VECTOR, STATE.ASSET_SEQ_NUM, STATE.CREATE_TM, STATE.EXPIRATION_TM, " +
					"STATE.MIGRATION_TM, STATE.ASSET_TOTAL_PARTS, STATE.ASSET_PART_SIZE, STATE.ASSET_LENGTH, STATE.ASSET_STORED_LENGTH, " +
					"STATE.ASSET_TYPE, STATE.ASSET_CHECKSUM, STATE.ASSET_DELETE_IND, STATE.MOUNT_ID, " +
					"STATE.VIRUS_SCAN_STATUS, STATE.VIRUS_SCAN_DEFN, STATE.VIRUS_SCAN_DEFN_TM, STATE.VIRUS_SCAN_TM, " +
					"STATE.FS_VERSION, STATE.MOUNT_FILE_PATH, STATE.ASSET_PATH, STATE.ASSET_TYPE_IND, " +
					"STATE.ASSET_METADATA, STATE.TAG_1, STATE.TAG_2, STATE.TAG_3, STATE.TAG_4, STATE.TAG_5, " +
					"STATE.TAG_6, STATE.TAG_7, STATE.TAG_8, STATE.TAG_9, STATE.TAG_10, STATE.TAG_11, STATE.TAG_12, " +
					"STATE.TAG_13, STATE.TAG_14, STATE.TAG_15, STATE.TAG_16, STATE.TAG_17, STATE.TAG_18, " +
					"STATE.TAG_19, STATE.TAG_20, STATE.TAG_21, STATE.TAG_22, STATE.TAG_23, STATE.TAG_24, " +
					"STATE.TAG_25, STATE.TAG_26, STATE.TAG_27, STATE.TAG_28, STATE.TAG_29, STATE.TAG_30, " +
					"STATE.TAG_31, STATE.TAG_32) VALUES ( NEWSTATE.STRIPE_INDEX, NEWSTATE.ASSET_KEY, " +
					"NEWSTATE.ASSET_BUCKET, NEWSTATE.SITE_ID, NEWSTATE.TOPIC_ID, NEWSTATE.ASSET_SITE_ID, " +
					"NEWSTATE.OWNER_SITE_ID, NEWSTATE.ASSET_VERSION, NEWSTATE.ASSET_VECTOR, NEWSTATE.ASSET_SEQ_NUM, " +
					"NEWSTATE.CREATE_TM, NEWSTATE.EXPIRATION_TM, NEWSTATE.MIGRATION_TM, NEWSTATE.ASSET_TOTAL_PARTS, NEWSTATE.ASSET_PART_SIZE, " +
					"NEWSTATE.ASSET_LENGTH, NEWSTATE.ASSET_STORED_LENGTH, NEWSTATE.ASSET_TYPE, " +
					"NEWSTATE.ASSET_CHECKSUM, NEWSTATE.ASSET_DELETE_IND, NEWSTATE.MOUNT_ID, " +
					"NEWSTATE.VIRUS_SCAN_STATUS, NEWSTATE.VIRUS_SCAN_DEFN, NEWSTATE.VIRUS_SCAN_DEFN_TM, " +
					"NEWSTATE.VIRUS_SCAN_TM, NEWSTATE.FS_VERSION,  NEWSTATE.MOUNT_FILE_PATH, NEWSTATE.ASSET_PATH, " +
					"NEWSTATE.ASSET_TYPE_IND, NEWSTATE.ASSET_METADATA, NEWSTATE.TAG_1, NEWSTATE.TAG_2, " +
					"NEWSTATE.TAG_3, NEWSTATE.TAG_4, NEWSTATE.TAG_5, NEWSTATE.TAG_6, NEWSTATE.TAG_7, NEWSTATE.TAG_8, " +
					"NEWSTATE.TAG_9, NEWSTATE.TAG_10, NEWSTATE.TAG_11, NEWSTATE.TAG_12, NEWSTATE.TAG_13, " +
					"NEWSTATE.TAG_14, NEWSTATE.TAG_15, NEWSTATE.TAG_16, NEWSTATE.TAG_17, NEWSTATE.TAG_18, " +
					"NEWSTATE.TAG_19, NEWSTATE.TAG_20, NEWSTATE.TAG_21, NEWSTATE.TAG_22, NEWSTATE.TAG_23, " +
					"NEWSTATE.TAG_24, NEWSTATE.TAG_25, NEWSTATE.TAG_26, NEWSTATE.TAG_27, NEWSTATE.TAG_28, " +
					"NEWSTATE.TAG_29, NEWSTATE.TAG_30, NEWSTATE.TAG_31, NEWSTATE.TAG_32)";

	String DELETE_DUPLICATE_STATE =
			" /* HA_QRY_41 */ DELETE /*+ INDEX(%TABLENAME_UQF% %TABLENAME_UQF%_PK) */ FROM %TABLENAME% WHERE STRIPE_INDEX=? AND " +
					"ASSET_KEY=? AND SITE_ID=? AND TOPIC_ID=? AND CREATE_TM<>(SELECT MAX(CREATE_TM) FROM %TABLENAME% " +
					"WHERE STRIPE_INDEX=? AND ASSET_KEY=? AND ASSET_BUCKET=? AND SITE_ID=? AND TOPIC_ID=?)";

	String QUERY_CHECK_PAYLOAD =
			" /* HA_QRY_42 */ SELECT /*+ INDEX( %TABLENAME_UQF% %TABLENAME_UQF%_PK) */ ASSET_PART_NUM FROM %TABLENAME% WHERE " +
					"STRIPE_INDEX=? AND SITE_ID=? AND ASSET_VERSION=? AND ASSET_KEY=? AND ASSET_BUCKET=? AND " +
					"CREATE_TM=? AND TOPIC_ID=? ORDER BY ASSET_PART_NUM";
}
