//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.18 at 11:29:51 AM IST 
//


package com.jaxb.usecase;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.jaxb.usecase package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _UseCases_QNAME = new QName("", "use-cases");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.jaxb.usecase
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link UseCasesType }
     * 
     */
    public UseCasesType createUseCasesType() {
        return new UseCasesType();
    }

    /**
     * Create an instance of {@link ScenarioType }
     * 
     */
    public ScenarioType createScenarioType() {
        return new ScenarioType();
    }

    /**
     * Create an instance of {@link UseCaseType }
     * 
     */
    public UseCaseType createUseCaseType() {
        return new UseCaseType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UseCasesType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "use-cases")
    public JAXBElement<UseCasesType> createUseCases(UseCasesType value) {
        return new JAXBElement<UseCasesType>(_UseCases_QNAME, UseCasesType.class, null, value);
    }

}
